name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize Line Endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol crlf
          git add --renormalize .
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Run linter
        run: dotnet format --verify-no-changes --verbosity diagnostic
        
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.11

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration Release --no-restore \
        /p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
        /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
        /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
        /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}

  test:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"
    
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
        if: always()

  pack:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'
          preferLatestVersion: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack
        run: |
          dotnet pack --configuration Release --no-build --output nupkgs \
          /p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
          /p:PackageVersion=${{ steps.gitversion.outputs.fullSemVer }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            nupkgs
